### ISSUE TITLE
[BUG] Plushies cant be placed on server

### ISSUE THREAD

**Issue by Maveric0484** [Link4real/Plushie-Mod#21]
To whom it may concern:

I have downloaded and installed the plushie mod onto my Minecraft server. I am OP so I can see the plushies in my creative inventory, so I know it works. When I try to place them in the world, they just disappear.

I see on the website it says "The mod now requires [Architectury API]" Which I have also installed and it still does not work. Is there something else I can do?

Maveric

**Comment by Link4real** [comment]
Thank you for reaching out!
Could you please also tell me which version and which modloader you used?
