### ISSUE TITLE
[request] PlayerPlushie

### ISSUE THREAD

**Issue by CKY-** [Link4real/Plushie-Mod#23]
It would be amazing if there was a default steve plushie that could be renamed with a nametag or in an anvil to a players IGN and it take on the skin. I know this has caching issues and having to store the player skin. but I think it would be a lovely touch..

**Comment by Link4real** [comment]
We have already tried this, but due to missing APIs from Fabric or Forge, it is quite difficult to achieve. At this moment in development, it will _**not**_ be added!
