### ISSUE TITLE
The witch plushie is smaller than the other illagers and the pillager is larger than the other illagers

### ISSUE THREAD

**Issue by WaffleBender** [Link4real/Plushie-Mod#25]
![image](https://github.com/Link4real/Plushie-Mod/assets/140558721/60479b26-831b-4320-a8c0-7de12e6dd1b4)

**Comment by Link4real** [comment]
Thanks, I'll fix the pillager!
The problem with the witch is that if I made her taller, her hat would be higher than a block height, which would make the whole hitbox situation pretty messy. If you want parity, I'd have to sacrifice the height of the other illager plushies, which I don't think is necessary!
