### ISSUE TITLE
Translation of Plushie Mod in French 🇫🇷

### ISSUE THREAD

**Issue by OriginalSleeper** [Link4real/Plushie-Mod#27]
Hi,
I recently saw that you needed help with the translations of your mod,
(You said to put the translations here, in _Issues_, so here it is)
I'm French, and I saw your translation base on [pastebin](https://pastebin.com/qGU2sq6r),
So here is the French translation, I hope you will enjoy it (if you want to use it).
If there are any problems, please let me know.
_Have_ a nice day!_

[Plushie Mod Translation.json](https://github.com/Link4real/Plushie-Mod/files/14373005/Plushie.Mod.Translation.json)

**Comment by Link4real** [comment]
Yes, thank you very much!
I will definitely include this translation in an upcoming version!
Have a great day also!

**Comment by OriginalSleeper** [comment]
Thanks!
