### ISSUE TITLE
[Issue] Cannot pick up plushies after they've been placed in the world

### ISSUE THREAD

**Issue by jayofearth** [Link4real/Plushie-Mod#31]
Plushies Version: 1.5.0
MC Version: 1.21.1
Fabric Version: 0.16.5

Running the mod on a survival server. We can craft and place the plushies but they vanish when we try to break them to pick them up. I thought maybe it required a special tool like shears or silk touch but we still can't pickup the plushies.

**Comment by Link4real** [comment]
Thank you for your report!
Mojang changed a folder name and I didn't realise it!
Should be fixed now in v1.5.1!
